apiVersion: v1
kind: Secret
metadata:
  name: foodtracker-secrets
type: Opaque
data:
  # These values should be base64 encoded
  COSMOS_ENDPOINT: "YOUR-COSMOS-ENDPOINT-BASE64"  # Replace with your actual Cosmos DB endpoint
  COSMOS_KEY: "YOUR-COSMOS-KEY-BASE64"            # Replace with your actual Cosmos DB key
  TELEGRAM_BOT_TOKEN: "NzcyMzQ4NDY3NTpBQUc0cG5zTko0d09mQTQ2UVhPM3AyeGtEWElCSE1pMXJuWQ=="  # Base64 encoded token
  WEBHOOK_URL: ""      # To be filled during deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodtracker
  labels:
    app: foodtracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodtracker
  template:
    metadata:
      labels:
        app: foodtracker
    spec:
      containers:
      - name: foodtracker
        image: foodtrackeracr.azurecr.io/foodtracker:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: COSMOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: foodtracker-secrets
              key: COSMOS_ENDPOINT
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: foodtracker-secrets
              key: COSMOS_KEY
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: foodtracker-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: foodtracker-secrets
              key: WEBHOOK_URL
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: foodtracker
spec:
  selector:
    app: foodtracker
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 