name: Deploy to AKS

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: foodtracker
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}/foodtracker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: foodtracker-rg
        cluster-name: foodtracker-aks

    - name: Create Kubernetes secrets
      run: |
        kubectl create secret generic foodtracker-secrets \
          --from-literal=COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
          --from-literal=COSMOS_KEY=${{ secrets.COSMOS_KEY }} \
          --from-literal=TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy to AKS
      run: |
        kubectl apply -f kubernetes/foodtracker-deployment.yaml 